version: 2.1

#orbs:
#  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:10.15.2
    working_directory: ~/datashare-plugin-dataconnect
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages- # used if checksum fails
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test:unit

  test:
    docker:
      - image: circleci/node:10.15.2
    working_directory: ~/datashare-plugin-dataconnect
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages- # used if checksum fails
      - run:
          name: Run unit test
          command: yarn test:unit

#  build:
#    docker:
#      - image: circleci/node:10.15.2
#    working_directory: ~/datashare-plugin-dataconnect
#    steps:
#      - run:
#          name: Build
#          command: yarn build

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
#          filters:
#            tags:
#              only: /.*/
