version: 2.1

executors:
  global-executor:
    docker:
      - image: circleci/node:10.15.2
    working_directory: ~/datashare-plugin-dataconnect

commands:
  checkout-and-install:
    description: "A command to checkout and install the packages"
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages- # used if checksum fails
      - run:
          name: Install yarn dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor: global-executor
    steps:
      - checkout-and-install
      - run:
          name: Run yarn unit tests
          command: yarn test:unit

  release:
    executor: global-executor
    steps:
      - checkout-and-install
      - run:
          name: Make distribution
          command: yarn build
      - run:
          name: Release on Github
          command: |
            cd ~/datashare-plugin-dataconnect
            mkdir package
            cp package.json package
            cp -R dist package
            tar czf datashare-plugin-dataconnect-${CIRCLE_TAG}.tgz package
            zip -r datashare-plugin-dataconnect-${CIRCLE_TAG}.zip package
            upload_url=$(curl -X POST -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -d "{\"tag_name\":\"${CIRCLE_TAG}\", \"name\":\"${CIRCLE_TAG}\",\"body\":\"release ${CIRCLE_TAG}\"}" "https://api.github.com/repos/ICIJ/datashare-plugin-dataconnect/releases" | jq -r '.upload_url')
            upload_url="${upload_url%\{*}"
            echo "Uploading asset to release url: $upload_url"
            curl -X POST -s -m 120 -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" --data-binary "@/datashare-plugin-dataconnect/datashare-plugin-dataconnect-${CIRCLE_TAG}.zip" "$upload_url?name=datashare-plugin-dataconnect-${CIRCLE_TAG}.zip&label=datashare-plugin-dataconnect-${CIRCLE_TAG}.zip"
            curl -X POST -s -m 120 -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/gzip" --data-binary "@/datashare-plugin-dataconnect/datashare-plugin-dataconnect-${CIRCLE_TAG}.tgz" "$upload_url?name=datashare-plugin-dataconnect-${CIRCLE_TAG}.tgz&label=datashare-plugin-dataconnect-${CIRCLE_TAG}.tgz"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9.]*/
            branches:
              ignore: /.*/
