version: 2.1

jobs:
  install:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - run:
          name: Build
          command: yarn build

  test:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - run:
          name: Run tests
          command: yarn test:unit

workflows:
  version: 2
  build_workflow:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
